---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-cert
  namespace: whoami
spec:
  commonName: whoami.cert.containous.cloud
  secretName: whoami-cert
  dnsNames:
    #- app.org 
    - whoami.cert.containous.cloud
  issuerRef:
    name: ca-issuer 
    kind: Issuer
    #name: letsencrypt-staging
    #kind: ClusterIssuer
  renewBefore: 6m 
  duration: 1h

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: powpow-cert
  namespace: whoami
spec:
  commonName: powpow.cert.containous.cloud
  secretName: powpow-cert
  dnsNames:
    #- whoami.whoami.svc.cluster.local 
    - powpow.cert.containous.cloud
  issuerRef:
    name: ca-issuer 
    kind: Issuer
    #name: letsencrypt-staging
    #kind: ClusterIssuer
  renewBefore: 6m 
  duration: 1h
